spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testintegrationdb;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS pedido
  test:
    database:
      replace: none

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_schema: pedido
    database-platform: org.hibernate.dialect.H2Dialect

  liquibase:
    enabled: false

logging:
  level:
    root: INFO
